### ISSUE TITLE
HDFS for go-storage

### ISSUE THREAD

**Issue by Prnyself** [beyondstorage/go-service-hdfs#1]
## Description

Hadoop Distributed File System ([HDFS]) is a distributed file system developed for applications on large datasets. This project will implement the [go-storage] Storager interface for HDFS, enabling users to manipulate data on HDFS services through a unified interface.

## Roadmap

- [x] Choose a well maintained HDFS library
- [x] Implement all interface that Storager required
- [x] Setup integration tests
- [x] Add docs in [site](https://github.com/aos-dev/site)  https://github.com/beyondstorage/site/pull/228
- [x] Add examples in [example](https://github.com/aos-dev/go-storage-example) https://github.com/beyondstorage/go-storage-example/pull/25

[HDFS]: https://hadoop.apache.org/docs/r1.2.1/hdfs_design.html#Introduction
[go-storage]: https://github.com/aos-dev/go-storage

**Comment by Xuanwo** [comment]
@bokket is responsible for this issue.
